language: node_js
node_js: 6

services:
    - docker

before_install:
    - docker --version
    - docker build -t bugyik/apiary-cli:${TRAVIS_COMMIT} .
    - docker run --detach --entrypoint=/bin/sh --name ${TRAVIS_COMMIT} bugyik/apiary-cli:${TRAVIS_COMMIT} -c 'while true; do sleep 1; done;'
    - docker exec -it ${TRAVIS_COMMIT} npm install

script:
    - docker exec -it ${TRAVIS_COMMIT} npm run cs
    - docker exec ${TRAVIS_COMMIT} sh -c "npm run mock" &
    - sleep 3
    - docker exec -it ${TRAVIS_COMMIT} npm run coverage

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        VERSION=$(git describe | sed 's/^v//');
        echo $VERSION;
        echo ${DOCKER_PASSWORD} | docker login --username "${DOCKER_USERNAME}" --password-stdin;
        docker tag bugyik/apiary-cli:${TRAVIS_COMMIT} bugyik/apiary-cli:${VERSION};
        docker tag bugyik/apiary-cli:${TRAVIS_COMMIT} bugyik/apiary-cli:latest;
        docker push bugyik/apiary-cli:${VERSION};
        docker push bugyik/apiary-cli:latest;
        fi

deploy:
    provider: npm
    email: ${NPM_KEY}
    api_key:
        secure: ${NPM_EMAIL}
    on:
        tags: true
        repo: o5/apiary-cli
