version: '2'
services:
    app:
        build: .
        container_name: apiary-cli
        entrypoint: /bin/sh
        command: -c "npm install && echo && echo '*** HAPPY CODING! ***' && echo && while true; do sleep 1; done;" # this is a little hack :)

        volumes:
            - .:/src/apiary-cli/:cached
